import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./Components/NavBar/NavBar";
import AuthProvider from "@/providers/AuthProvider";
import { getAuthSession } from "@/util/auth"
import SideBar from "./Components/SideBar/SideBar";
import { StoreProvider } from "@/reduxe/StoreProvider";
import TosterProvider from "@/providers/TosterProvider";
import "@uploadthing/react/styles.css";
import dynamic from 'next/dynamic';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function  RootLayout({ children }) {
  const AuthProvider = dynamic(() => import("@/providers/AuthProvider"), { ssr: false });
  const session = await getAuthSession();
  let items=[]
  if(session){
     items=[{id:1,path:`/dashboard/${session.user.email}`,name:"Dashboard"},{id:3,path:"/courses",name:"Browse"}]
  }
  
  return (
    <html lang="en">
    
      <body className={inter.className}>
        <StoreProvider>
          <div className="wrapper">
              <AuthProvider>
                    <NavBar/>
                    <div className="AuthHome">
                      {session &&<SideBar items={items}/>}
                      <TosterProvider/>
                      {children}
                    </div>
              </AuthProvider>
          </div>
      </StoreProvider>
      </body>
      
    </html>
  );
}
